---
swagger: "2.0"
info:
  description: "This document describes mock API for IP whitelist"
  version: "1.0.0"
  title: "CSIRT-MU Whitelist"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cech@ics.muni.cz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
schemes:
- "http"
- "https"
paths:
  /:
    get:
      summary: "List all records"
      operationId: "list_records"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Array of all records"
          schema:
            $ref: "#/definitions/ArrayOfRecords"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      summary: "Create new record"
      operationId: "new_record"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Creates new record, comment is optional"
        required: true
        schema:
          $ref: "#/definitions/Record"
      responses:
        "201":
          description: "Object created, returns new object"
          schema:
            $ref: "#/definitions/Record"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Record:
    type: "object"
    required:
    - "ip"
    properties:
      ip:
        type: "string"
        example: "127.0.0.1, 192.168.1.125/24"
      port_from:
        type: "integer"
        format: "int32"
        example: 0
      port_to:
        type: "integer"
        format: "int32"
        example: 65535
      service:
        type: "string"
        example: "TCP port scan detection"
      expiration:
        type: "string"
        format: "date-time"
      report_email:
        type: "string"
        format: "email"
      comment:
        type: "string"
        example: "Example comment"
    example:
      ip: "192.168.1.25"
      port_from: 1
      port_to: 128
      service: "TCP port scan detection"
      expiration: "22.6.2021"
      report_email: "email@example.com"
      comment: "Sample comment"
      summary: "Example API Response, with object ID"
  ArrayOfRecords:
    type: "array"
    items:
      $ref: "#/definitions/Record"
