---
swagger: "2.0"
info:
  description: "This document describes mock API for DNSRPZ blacklist"
  version: "1.0.0"
  title: "CSIRT-MU DNS Blacklist Mocker"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cech@ics.muni.cz"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
schemes:
- "http"
- "https"
paths:
  /:
    get:
      tags:
      - "domain blacklist"
      summary: "Apparently single endpoint for everything"
      operationId: "get_list"
      produces:
      - "application/json"
      parameters:
      - name: "zone"
        in: "query"
        description: "white or black"
        required: false
        type: "string"
      - name: "action"
        in: "query"
        description: "list add or remove"
        required: true
        type: "string"
      - name: "domain"
        in: "query"
        required: false
        type: "string"
      - name: "entry"
        in: "query"
        description: "so far used only CNAME, in docs also A and AAAA"
        required: false
        type: "string"
      - name: "target"
        in: "query"
        description: "so far used only ., must correspond to entry (IPv4, IPv6, alias,\
          \ rpz-passthru for whitelist)"
        required: false
        type: "string"
      - name: "reason"
        in: "query"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/inline_response_200"
        "500":
          description: "server fail"
          schema:
            $ref: "#/definitions/inline_response_500"
      x-swagger-router-controller: "swagger_server.controllers.domain_blacklist_controller"
definitions:
  inline_response_200:
    type: "object"
    properties:
      error:
        $ref: "#/definitions/inline_response_200_error"
      result:
        type: "array"
        items:
          type: "string"
    example:
      error:
        mesg: "mesg"
        retval: 0
      result:
      - "result"
      - "result"
  inline_response_200_error:
    type: "object"
    properties:
      mesg:
        type: "string"
      retval:
        type: "integer"
    example:
      mesg: "mesg"
      retval: 0
  inline_response_500:
    type: "object"
    properties:
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
