[tool.poetry]
name = "malware-use-case-gateway-backend"
version = "0.1.0"
description = ""
authors = ["Dušan Tichý <469132@mail.muni.cz>"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = {version = "^0.14.0", extras = ["standard"]}
uvloop = "^0.15.3"
starlette = "^0.16.0"
strawberry-graphql = "^0.70.1"
websockets = "^9.1"
SQLAlchemy = "^1.4.22"
minio = "^7.1.0"
urllib3 = "^1.26.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
