[tool.poetry]
name = "airflow"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
blocker-api-mock-swagger-client = { path = "wheels/blocker_api_mock_swagger_client-1.0.0-py3-none-any.whl" }
dnsrpz-api-mock-swagger-client = { path = "wheels/dnsrpz_api_mock_swagger_client-1.0.0-py3-none-any.whl" }
whitelist-api-mock-swagger-client = {path = "wheels/whitelist_api_mock_swagger_client-1.0.0-py3-none-any.whl" }
xhtml2pdf = "^0.2.5"
pymisp = "^2.4.148"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
