[tool.poetry]
name = "observable-evaluator"
version = "0.1.0"
description = "This service is able to check whether an observable is malicious or not"
authors = ["Michal Čech <cech@ics.muni.cz>"]

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = {version = "^0.14.0", extras = ["standard"]}
uvloop = "^0.15.3"
starlette = "^0.16.0"
strawberry-graphql = "^0.70.1"
pyintelowl = "^3.1.4"
minio = "^7.1.0"
aiofiles = "^0.7.0"
dataclasses_json = "^0.5.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
