- name: prepare virtual machine with dockerized malware pipeline infrastructure
  hosts: target
  tasks:
    - name: install acl
      ansible.builtin.apt:
        name: acl
        state: present
      become: true

    - name: install pip
      apt:
        name: pip
        state: present
      become: true

    - name: install docker
      ansible.builtin.apt:
        name: docker
        state: latest
      become: true

    - name: ensure that docker is also installed with pip
      pip:
        name: docker
        state: present

    - name: install docker-compose
      ansible.builtin.apt:
        name: docker-compose
        state: present
      become: true

    - name: add docker user
      ansible.builtin.user:
        name: docker
        group: docker
        password: "{{ 'dockerheslo' | password_hash('sha512', 'suljeslana') }}"
        groups: docker,sudo
        append: true
        create_home: true
      become: true

    - name: Ensure service is enabled
      service:
        name: docker
        state: started

    - name: run docker-compose
      docker_compose:
        project_src: /vagrant
        build: yes
        state: present
      become: true
      become_user: docker
      become_method: sudo
